//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteThuChi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Account
    {
        [Required(ErrorMessage="Chưa nhập username")]
        public string Username { get; set; }
        [Required(ErrorMessage = "Chưa nhập password")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        public Nullable<System.DateTime> LoginDate { get; set; }
        public string FullName { get; set; }
    }
}
