//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteThuChi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Customer
    {
        public Customer()
        {
            this.IncomeLineUps = new HashSet<IncomeLineUp>();
            this.OutcomeLineUps = new HashSet<OutcomeLineUp>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "Chưa nhập tên khách hàng")]
        public string CustomerName { get; set; }
         [Required(ErrorMessage = "Chưa nhập địa chỉ khách hàng")]
        public string CustomerAddress { get; set; }
    
        public virtual ICollection<IncomeLineUp> IncomeLineUps { get; set; }
        public virtual ICollection<OutcomeLineUp> OutcomeLineUps { get; set; }
    }
}
