//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteThuChi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomeLineUp
    {
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<decimal> Asset { get; set; }
        public Nullable<System.DateTime> InputDate { get; set; }
        public string Notes { get; set; }
        public Nullable<int> IncomeId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Income Income { get; set; }
    }
}
