//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteThuChi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Income
    {
        public Income()
        {
            this.IncomeLineUps = new HashSet<IncomeLineUp>();
        }
    
        public int Id { get; set; }
        [DataType(DataType.DateTime)]
        [Required(ErrorMessage = "Chưa nhập IncomeDate")]
        public Nullable<System.DateTime> IncomeDate { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        [Required(ErrorMessage="Chưa nhập IncomeName")]
        public string IncomeName { get; set; }
    
        public virtual ICollection<IncomeLineUp> IncomeLineUps { get; set; }
    }
}
