//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteThuChi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestDbEntities1 : DbContext
    {
        public TestDbEntities1()
            : base("name=TestDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Accounts { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Income> Incomes { get; set; }
        public DbSet<IncomeLineUp> IncomeLineUps { get; set; }
        public DbSet<Outcome> Outcomes { get; set; }
        public DbSet<OutcomeLineUp> OutcomeLineUps { get; set; }
    }
}
