//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteThuChi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outcome
    {
        public Outcome()
        {
            this.OutcomeLineUps = new HashSet<OutcomeLineUp>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> OutcomeDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string OutcomeName { get; set; }
    
        public virtual ICollection<OutcomeLineUp> OutcomeLineUps { get; set; }
    }
}
